# fly.toml app configuration file generated for gbs-tools-wispy-wildflower-8437 on 2024-11-13T17:14:55-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gbs-tools-wispy-wildflower-8437'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
